name: deepkt-irt
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26
  - pandas=2.1
  - scipy=1.11
  - pytorch::pytorch=2.3
  - pytorch::torchvision=0.18
  - pytorch::torchaudio=2.3
  - pip:
      - pytorch-lightning==2.4.0
      - pyarrow==16.1.0
      - typer==0.12.3
      - rich==13.7.1
      - pykt-toolkit==0.0.37
      - hydra-core==1.3.2
